"""Changed Stats column names

Revision ID: 47a1de175738
Revises: 72987b8f57b8
Create Date: 2022-05-19 17:42:33.059626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a1de175738'
down_revision = '72987b8f57b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'hb_wins', new_column_name='hb_correct')
    op.alter_column('stats', 'hb_plays', new_column_name='hb_total')
    op.alter_column('stats', 'psyc_wins', new_column_name='psyc_correct')
    op.alter_column('stats', 'psyc_plays', new_column_name='psyc_total')
    op.alter_column('stats', 'cs_wins', new_column_name='cs_correct')
    op.alter_column('stats', 'cs_plays', new_column_name='cs_total')
    op.alter_column('stats', 'econ_wins', new_column_name='econ_correct')
    op.alter_column('stats', 'econ_plays', new_column_name='econ_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'hb_correct', new_column_name='hb_wins')
    op.alter_column('stats', 'hb_total', new_column_name='hb_plays')
    op.alter_column('stats', 'psyc_correct', new_column_name='psyc_wins')
    op.alter_column('stats', 'psyc_total', new_column_name='psyc_plays')
    op.alter_column('stats', 'cs_correct', new_column_name='cs_wins')
    op.alter_column('stats', 'cs_total', new_column_name='cs_plays')
    op.alter_column('stats', 'econ_correct', new_column_name='econ_wins')
    op.alter_column('stats', 'econ_total', new_column_name='econ_plays')
    
    # ### end Alembic commands ###
