"""Added Stats table

Revision ID: 72987b8f57b8
Revises: 
Create Date: 2022-05-19 17:36:33.236967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72987b8f57b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hb_wins', sa.Integer(), nullable=True),
    sa.Column('hb_plays', sa.Integer(), nullable=True),
    sa.Column('psyc_wins', sa.Integer(), nullable=True),
    sa.Column('psyc_plays', sa.Integer(), nullable=True),
    sa.Column('cs_wins', sa.Integer(), nullable=True),
    sa.Column('cs_plays', sa.Integer(), nullable=True),
    sa.Column('econ_wins', sa.Integer(), nullable=True),
    sa.Column('econ_plays', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
